### ISSUE TITLE
Could `resolve` return a promise

### ISSUE THREAD

**Issue by eddieajau** [marcusberner/sandal#6]
I'm really loving your implementation, but I'm wondering if you've given any thought to allow the `resolve` method to return a promise if a callback is not supplied?

**Comment by marcusberner** [comment]
Hi,

Thanks for the feedback. Thats not something I have thought about but it makes sense. Will look into it later today if I find some time.

**Comment by marcusberner** [comment]
Is this the behaviour you would expect?

``` javascript
sandal.resolve()
.then(function(a, b, c, e) {

}).error(function (error) {

})

// or

sandal.resolve(['a', 'b', 'c', 'e'])
.then(function(a, b, c, e) {

}).error(function (error) {

})
```

**Comment by eddieajau** [comment]
Close. It would be something like this:

``` js
sandal.resolve()
    .then(function (arrayOfThings) {
    });

sandal.resolve()
    .spread(function (a, b, c, d) {
    });

sandal.resolve('orm')
    .then(function (orm) {
    })
    .catch(function (err)) {
    }
    .done();

// or
sandal.resolve(['orm', 'logger'])
    .spread(function (orm, logger) {
    })
    .done(null, console.error);
```

**Comment by kesla** [comment]
Would it be possible to add promise support as a separate project? Especially when including sandal in the browser, I'm guessing that adding support for promises would be quite an overhead?

**Comment by marcusberner** [comment]
The largest overhead will probably be complexity rather than performance. Adding it as an extension in another project could make sense but I will play around with different solutions.

**Comment by marcusberner** [comment]
I created an extension that adds promises support using the q library. Dependencies are provided as an array, thus both then() and spread() can be used as proposed. Check it out [sandal-promise](https://github.com/marcusberner/sandal-promise). It's published to npm and bower.
